package com.cybersoft.application_management.exception;

import org.springframework.http.HttpStatus;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT),
    USER_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED),
    FORM_TYPE_NOT_FOUND(HttpStatus.NOT_FOUND),
    FORM_TYPE_ALREADY_EXISTS(HttpStatus.CONFLICT),
    ATTACHMENT_NOT_FOUND(HttpStatus.NOT_FOUND),
    ATTACHMENT_ALREADY_EXISTS(HttpStatus.CONFLICT),
    INVALID_FILE_TYPE(HttpStatus.BAD_REQUEST),
    FILE_SIZE_EXCEEDED(HttpStatus.BAD_REQUEST),
    APPLICATION_FORM_NOT_FOUND(HttpStatus.NOT_FOUND),
    APPLICATION_ALREADY_APPROVED(HttpStatus.CONFLICT),
    APPLICATION_ALREADY_REJECTED(HttpStatus.CONFLICT),
    APPLICATION_ALREADY_CANCELLED(HttpStatus.CONFLICT),
    INVALID_APPLICATION_STATUS_TRANSITION(HttpStatus.BAD_REQUEST),
    INACTIVE_FORM_TYPE(HttpStatus.BAD_REQUEST),
    FORBIDEN_OPERATION(HttpStatus.FORBIDDEN),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED),
    FORBIDDEN(HttpStatus.FORBIDDEN),
    INVALID_JWT(HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    ACCESS_DENIED(HttpStatus.FORBIDDEN),
    METHOD_NOT_ALLOWED(HttpStatus.METHOD_NOT_ALLOWED),
    UNSUPPORTED_MEDIA_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE),

    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED),
    REFRESH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED);

    private final HttpStatus httpStatus;

}
